services:
  app:
    build:
      args:
        INSTALL_DEV_DEPS: "true"
    command: [ "fastapi", "dev", "--host", "0.0.0.0", "--port", "8000" ]
    volumes:
      - ./.cache:/app/.cache
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: ./pyproject.toml
