services:
  app:
    build:
      args:
        INSTALL_DEV_DEPS: "true"
    command: [ "pytest", "--cov", "app" ]
    volumes:
      - ./var/cov-report:/app/var/cov-report

  postgres:
    volumes:
      - ./var/pgdata-test:/var/lib/postgresql/data
